/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, XASInterface;

__attribute__((visibility("hidden")))
@interface XASDemoXASManager : NSObject {
	XASInterface* xasInterface;
	int sessionID;
	NSString* token;
	NSString* errorMessage;
}
@property(readonly, assign) NSString* errorMessage;
@property(readonly, assign) NSString* token;
@property(readonly, assign) int sessionID;
+(id)sharedInstance;
-(void).cxx_destruct;
-(id)init;
-(int)checkApp;
@end

