/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface XASInterface : NSObject {
	int SID;
	NSString* Token;
}
@property(readonly, assign, nonatomic) NSString* Token;
@property(readonly, assign, nonatomic) int SID;
+(id)getXASVersion;
-(id)errorMessage:(int)message;
-(int)checkApp:(id)app appInfo:(id)info identifier:(id)identifier;
-(int)checkApp:(id)app appInfo:(id)info;
-(id)init;
@end

